# 🩵 Étape 1 — Nettoyage du dataset *Life Expectancy (WHO)*

## 🎯 Objectif
Rendre les données brutes exploitables :
- Identifier et gérer les valeurs manquantes  
- Corriger les types de variables  
- Détecter les doublons et les valeurs aberrantes  
- Préparer un dataset propre pour l’analyse exploratoire  

---

In [8]:
import pandas as pd
import numpy as np
from pathlib import Path

# ➜ mets ici ton chemin ABSOLU (celui qui a marché)
RAW = Path(r"C:\Users\dinay\Desktop\laplateforme\B2_IA\dazzle-dash\dazzle-dash\data\raw\Life Expectancy Data.csv")

# ➜ on construit automatiquement le chemin "clean" à côté de /data/raw
CLEAN = RAW.parent.parent / "clean" / "who_life_clean.csv"
CLEAN.parent.mkdir(parents=True, exist_ok=True)

print("RAW :", RAW)
print("CLEAN :", CLEAN)

RAW : C:\Users\dinay\Desktop\laplateforme\B2_IA\dazzle-dash\dazzle-dash\data\raw\Life Expectancy Data.csv
CLEAN : C:\Users\dinay\Desktop\laplateforme\B2_IA\dazzle-dash\dazzle-dash\data\clean\who_life_clean.csv

In [9]:
# 📄 Lecture du dataset brut + affichage des 5 premières lignes
df = pd.read_csv(RAW, sep=None, engine="python")
df.columns = df.columns.str.strip()  # enlève les espaces dans les noms de colonnes

print("Dimensions du dataset :", df.shape)
df.head()

Dimensions du dataset : (2938, 22)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [10]:
# 📄 Lecture du dataset brut + affichage des 5 premières lignes
df = pd.read_csv(RAW, sep=None, engine="python")
df.columns = df.columns.str.strip()  # enlève les espaces dans les noms de colonnes

print("Dimensions du dataset :", df.shape)
df.head()

Dimensions du dataset : (2938, 22)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5